apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-application
spec:
  description: |
    This Task deploys an application to a Kubernetes cluster using kubectl
  params:
    - name: pathToContext
      type: string
      description: The path to the directory containing yaml files
      default: .
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: deploy.yaml
    - name: imageUrl
      type: string
      description: Url of image repository
    - name: imageTag
      type: string
      description: Tag of the images to be used.
      default: "latest"
  workspaces:
    - name: source
      description: Holds the git repo
  steps:
    - name: update-yaml
      image: alpine
      env:
        - name: REGISTRY_URL
          valueFrom:
            configMapKeyRef:
              name: registry-config
              key: url
      script: |
        #!/bin/sh
        set -e
        echo "Updating deployment image to ${REGISTRY_URL}/$(params.imageUrl):$(params.imageTag)"
        sed -i -e "s;IMAGE;${REGISTRY_URL}/$(params.imageUrl):$(params.imageTag);g" $(workspaces.source.path)/$(params.pathToContext)/$(params.pathToYamlFile)
    - name: deploy-app
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        echo "Deploying application..."
        kubectl apply -f $(workspaces.source.path)/$(params.pathToContext)/$(params.pathToYamlFile)